<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>{module_pagetitle}</title>


<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
<link href="/css/styles.css" rel="stylesheet">
<link href="/css/nav.css" rel="stylesheet">

<link href="/css/template.css" rel="stylesheet">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<!-- ADD JPUSHMENU -->
<link href="/css/jPushMenu.css" rel="stylesheet">
<script type="text/javascript" src="/js/jPushMenu.js"></script>

<!-- ADD WEBTICKER -->
<link href="/css/webticker.css" rel="stylesheet">
<script type="text/javascript" src="/js/jquery.webticker.js"></script>

<!-- ADD CYCLE -->
<script type="text/javascript" src="/js/jquery.cycle2.js"></script>
<script type="text/javascript" src="/js/jquery.cycle2.carousel.min.js"></script>

<!-- ADD RESPONSIVE TABS -->
<link rel="stylesheet" href="/css/responsive-tabs.css">
<script type="text/javascript" src="/js/jquery.responsiveTabs.min.js"></script>

<!-- ADD DATE PICKER -->
<link href="/css/bootstrap-datepicker.min.css" rel="stylesheet" />
<script type="text/javascript" src="/js/bootstrap-datepicker.js"></script>


<!-- ADD FANCYBOX -->
<link rel="stylesheet" href="/js/fancy/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="/js/fancy/jquery.fancybox.pack.js?v=2.1.5"></script>

<!-- ADD BOOTSTRAP JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/js/dropdown.js"></script>


<script type="text/javascript" src="/js/javascript.js"></script>