<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>{module_pagetitle}</title>


<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
<link href="/css/styles.css" rel="stylesheet">
<link href="/css/nav.css" rel="stylesheet">
<link href="/css/webticker.css" rel="stylesheet">
<link href="/css/template.css" rel="stylesheet">
<link href="https://rawgit.com/takien/jPushMenu/master/css/jPushMenu.css" rel="stylesheet">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="https://rawgit.com/takien/jPushMenu/master/js/jPushMenu.js"></script>
<script type="text/javascript" src="/js/jquery.webticker.js"></script>
<script type="text/javascript" src="http://malsup.github.io/jquery.cycle2.js"></script>
<script type="text/javascript" src="http://malsup.github.io/min/jquery.cycle2.carousel.min.js"></script>

<link rel="stylesheet" href="https://rawgit.com/jellekralt/Responsive-Tabs/master/css/responsive-tabs.css">
<script type="text/javascript" src="https://rawgit.com/jellekralt/Responsive-Tabs/master/js/jquery.responsiveTabs.min.js"></script>




<!-- Add fancyBox -->
<link rel="stylesheet" href="/js/fancy/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="/js/fancy/jquery.fancybox.pack.js?v=2.1.5"></script>


<script type="text/javascript" src="/js/javascript.js"></script>