{% comment -%}
{% assign searchID = "4425" -%}
{% assign resultsPageID = "/search" -%}
{% endcomment -%}
<div class="search">
    <div class="site-search">
        <form name="catsearchform11819" method="post" action="/Default.aspx?SiteSearchID={{searchID}}&amp;PageID={{resultsPageID}}">
            <div class="input-group">
                <input class="form-control" type="text" name="CAT_Search" id="CAT_Search" placeholder="Search">
                <span class="input-group-addon"><input type="submit" value="Search"></span>
            </div>
        </form>
    </div>
</div>
